version: 2.1

jobs:
  arm64-native:
    machine:
      image: ubuntu-2004:current
      resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "./gradlew bootBuildImage"

workflows:
  say-hello-workflow:
    jobs:
      - arm64-native
